[base]
stream_type = "kafka"

[producer]
bootstrap_servers = ["broker:29092"]

[consumer]
bootstrap_servers = ["broker:29092"]
topic = "MMA_GW_Events_shared"
group_id = "mma-GW-Livingston"
enable_auto_commit = true
auto_offset_reset = "earliest"