client_id: '0'
generator_configs:
  # Device to use: cpu or cuda
  device: "cpu"
  logging_id: "LIGO_Livingston"
  logging_output_dirname: "<absolute path to repo>/examples/output"
  logging_output_filename: "result"

inference_configs:
  batch_size: 2
  dataset_path: "<absolute path to downloaded data directory>/Feb_Events/GW200129_065458_1264314069.hdf5"
  length: None

model_configs:
  checkpoint_dir: "<absolute path to downloaded data directory>/2channel_ckpts/detector_1_sub_mod_A.ckpt"

comm_configs:
  octopus_configs:
      topic: 'MMA_GW_Events_shared' 
      group_id: 'mma-GW-Livingston'
