client_id: '1'
generator_configs:
  # Device to use: cpu or cuda
  device: "cpu"
  logging_id: "LIGO_Hanford"
  logging_output_dirname: "<absolute path to repo>/examples/output"
  logging_output_filename: "result"

inference_configs:
  batch_size: 8
  dataset_path: "<absolute path to downloaded data directory>/Inference_dataset/truncated_whitened_strains_GW170817_1187006834_tukey.hdf5"
  length: None

model_configs:
  checkpoint_dir: "<absolute path to downloaded data directory>/2channel_ckpts/detector_2_sub_mod_B.ckpt"

comm_configs:
  octopus_configs:
      topic: 'MMA_GW_Events_shared'
      group_id: 'mma-GW-Hanford'
  proxystore_configs:
      enable_proxystore: True
      connector_type: "EndpointConnector"
      connector_configs:
        endpoints: ["48ce2ca5-26dc-4b4b-9066-4150e595b5a7","c7b0e638-2284-420a-83e7-c9d007881a60"]
        #detector2 endpoint, server endpoint

      # connector_type: "FileConnector"
      # connector_configs:
      #   store_dir: "/scratch/bcbw/parthpatel7173/proxystore"