client_id: "1"
generator_configs:
  # Device to use: cpu or cuda
  device: "cpu"
  logging_id: "LIGO_Hanford"
  logging_output_dirname: "/app/examples/output"
  logging_output_filename: "result"

inference_configs:
  batch_size: 8
  dataset_path: "/app/MMA_GravitationalWave_Data/Inference_dataset/GW200129_065458_1264314069.hdf5"
  length: None

model_configs:
  checkpoint_dir: "/app/MMA_GravitationalWave_Data/2channel_ckpts/detector_2_sub_mod_B.ckpt"

comm_configs:
  octopus_configs:
    topic: "MMA_GW_Events_shared"
    group_id: "mma-GW-Hanford"
  proxystore_configs:
    enable_proxystore: True
    connector_type: "EndpointConnector"
    connector_configs:
      endpoints: ["PROXYSTORE_SERVER_ENDPOINT", "PROXYSTORE_DETECTOR_ENDPOINT"]
      #detector2 endpoint, server endpoint

    # connector_type: "FileConnector"
    # connector_configs:
    #   store_dir: "/scratch/bcbw/parthpatel7173/proxystore"
