client_configs:
  generator_configs:
    do_inference: True
  comm_configs:
    # octopus_configs:
    compressor_configs:
      enable_compression: False

server_configs:
  aggregator_kwargs:
    # Device to use: cpu or cuda
    device: "cpu"
    post_process_configs:
      width: 2000
      threshold: 0.99

  logging_output_dirname: "/app/examples/output"
  logging_output_filename: "result"

  model_configs:
    checkpoint_dir: "/app/MMA_GravitationalWave_Data/2channel_ckpts"

  # define server side kafka parameters here like consumer settings (offset policy)
  comm_configs:
    octopus_configs:
      topic: "MMA_GW_Events_shared"
      group_id: "mma-GW-server"
