client_configs:
  generator_configs:
    do_inference: True
  comm_configs:
    # octopus_configs:
    compressor_configs:
      enable_compression: False

server_configs:
  aggregator_kwargs:
    # Device to use: cpu or cuda
    device: "cpu"
    post_process_configs:
      width: 2000
      threshold: 0.99

  logging_output_dirname: "/app/examples/output"
  logging_output_filename: "result"

  model_configs:
    checkpoint_dir: "/app/MMA_GravitationalWave_Data/2channel_ckpts"

  # define server side kafka parameters here like consumer settings (offset policy)
  comm_configs:
    stream_config: "examples/configs/streaming/files/FLserver.toml"
    producer_topic: "MMA_GW_Events_shared"
    proxystore_configs:
      enable_proxystore: True
      connector_type: "FileConnector"
      connector_configs:
        store_dir: "/app/ps-out"
      # connector_type: "EndpointConnector"
      # connector_configs:
      #   endpoints:
      #     [
      #       "PROXYSTORE_SERVER_ENDPOINT",
      #       "PROXYSTORE_DETECTOR0_ENDPOINT",
      #       "PROXYSTORE_DETECTOR1_ENDPOINT",
      #     ]